### ISSUE TITLE
Showplan song selection

### ISSUE THREAD

**Issue by djjavo** [radiowarwick/digiplay-laravel#43]
When clicking load on a track in studio_play, the next available track in the showplan should be automatically selected.

**Comment by connor642** [comment]
I did consider this. But effort (I may look into this again but I think people can learn that next song won't load)

**Comment by djjavo** [comment]
I agree that people can learn, but it is a good feature from a usability point of view.

**Comment by connor642** [comment]
True. But I'm sure all the new people will learn without it
