### ISSUE TITLE
File selection becomes unresponsive when undefined file is 'uploaded'.

### ISSUE THREAD

**Issue by willllhallll** [radiowarwick/digiplay-laravel#44]
The file selection button on the [Audio Upload](https://beta.radio.warwick.ac.uk/audio/upload) page becomes unresponsive if no file is selected before clicking upload. 

### Expected
Uploading should be prevented before a file is selected (Disable upload button?).

### Actual
When no file is specified, clicking upload results in a '100% - undefined' to be showed on the progress bar and the file selection button becomes unresponsive. 

### Image
![image](https://user-images.githubusercontent.com/29780384/54346153-81badd00-463c-11e9-9d19-b6cc8cf98f0d.png)

**Comment by willllhallll** [comment]
### Steps to Reproduce
1. Visit the Audio Upload Page.
2. Without selecting a file, click the 'upload' button. 
3. Try to click the file selection button. It is now unresponsive.

**Comment by connor642** [comment]
Thanks! This doesn't look like it'll be too difficult to fix, will sort it
out later today.
